### ISSUE TITLE
Adjusting dependencies to JupySQL

### ISSUE THREAD

**Issue by idomic** [jtkiley/carma_python#2]
I think it'll be beneficial for you to use [Jupysql](https://github.com/ploomber/jupysql) in your repo as we've added support in many interactive features on top of `ipython-sql`. There's backward compatibility so it's just changing the dependency.

**Comment by jtkiley** [comment]
Duplicate of #1.

**Comment by idomic** [comment]
Sorry for this!

**Comment by jtkiley** [comment]
@idomic Thanks for the heads-up about `ipython-sql` pointing to `jupysql` for future work over on #1. It looks good on my end after adjusting the connection string syntax.
